import { ReportData } from "./types";

export const MOCK_FULL_DATA: ReportData = {
  reportTitle: "New Report",
  pageSize: 'A4',
  orientation: 'portrait',
  datePeriod: "May 2024",
  tags: [],
  sections: [
    { id: 'sec-cover', type: 'cover' }
  ],
  floatingElements: [],
  themeColor: '#ffffff',
  accentColor: '#E8B931',
  cardColor: '#f9fafb',
  textColor: '#1a1a1a',
  h1Color: '#1a1a1a',
  h2Color: '#1a1a1a',
  h3Color: '#4b5563',
  descColor: '#6b7280',
  fontFamily: 'sans',
  borderRadius: 'xl',
  dealsGoal: 0,
  dealsCount: 0,
  conversionGoal: 0,
  conversionCount: 0,
  listContacts: 0,
  listDeals: 0,
  summary: "",
  recommendations: [],
  contactCount: 0,
  dealCount: 0,
  dealsValue: 0,
  growthLabels: [],
  growthDeals: [],
  growthContacts: [],
  dealSources: [],
  accountContacts: [],
  emailsSentGoal: 0,
  emailsOpenedGoal: 0,
  linkClicksGoal: 0,
  actualSent: 0,
  actualOpens: 0,
  actualClicks: 0,
  actualReplies: 0,
  metricsEmailsSent: 0,
  metricsOpens: 0,
  metricsOpenRate: "0%",
  sentTrend: [],
  opensTrend: [],
  linkClicksTotal: 0,
  linkClickRateStr: "0%",
  funnelSent: 0,
  funnelOpened: 0,
  funnelClicked: 0,
  engagementOpensTrend: [],
  engagementClicksTrend: [],
  unsubscribes: 0,
  unsubscribeRateStr: "0%",
  repliesTotal: 0,
  campaignsPerformance: []
};
