import { ReportData } from "./types";

export const MOCK_FULL_DATA: ReportData = {
  reportTitle: "Email Marketing Case Study",
  pageSize: 'A4',
  orientation: 'landscape',
  datePeriod: "03/24/2026 - 04/22/2026",
  tags: ["Marketing", "Case Study"],
  sections: [
    { id: 'sec-cover', type: 'cover' },
    { id: 'sec-metrics-overview', type: 'metrics_overview' },
    { id: 'sec-report-main', type: 'report_main' },
    { id: 'sec-distribution', type: 'distribution' },
    { id: 'sec-engagement', type: 'engagement' },
    { id: 'sec-grid-metrics', type: 'grid_metrics' },
    { id: 'sec-trends-opens', type: 'trends_opens' },
    { id: 'sec-funnel', type: 'funnel' },
    { id: 'sec-performance', type: 'performance' },
    { id: 'sec-thanks', type: 'thanks' }
  ],
  floatingElements: [],
  dealsGoal: 10000,
  dealsCount: 1637,
  conversionGoal: 10000,
  conversionCount: 5581,
  listContacts: 5734,
  listDeals: 3734,
  summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, seodo eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  recommendations: [
    "We recommend investigating the -31.76% decline in open rate and the 81.15% unsubscribe rate to identify root causes.",
    "We should analyze campaigns with unusually high bounce rates to clean contact lists.",
    "We propose leveraging the 31.59% link click rate by optimizing calls-to-action."
  ],
  contactCount: 2871,
  dealCount: 4603,
  dealsValue: 5871,
  growthLabels: ['Jan', 'Feb', 'Mar', 'Apr', 'May'],
  growthDeals: [100, 120, 150, 180, 210],
  growthContacts: [500, 600, 750, 900, 1100],
  dealSources: [
    { id: '1', source: 'Direct', value: 450 },
    { id: '2', source: 'Referral', value: 300 },
    { id: '3', source: 'Social', value: 250 }
  ],
  accountContacts: [
    { id: '1', name: 'Acme Corp', contacts: 50, deals: 5 },
    { id: '2', name: 'Global Industries', contacts: 120, deals: 12 }
  ],
  emailsSentGoal: 10000,
  emailsOpenedGoal: 5000,
  linkClicksGoal: 2000,
  actualSent: 6344,
  actualOpens: 5924,
  actualClicks: 6581,
  actualReplies: 80000,
  metricsEmailsSent: 6500,
  metricsOpens: 3200,
  metricsOpenRate: '49.23%',
  sentTrend: [100, 150, 130, 170, 200],
  opensTrend: [50, 75, 65, 85, 100],
  linkClicksTotal: 1500,
  linkClickRateStr: '23.08%',
  funnelSent: 10000,
  funnelOpened: 5000,
  funnelClicked: 2000,
  engagementOpensTrend: [40, 60, 50, 70, 80],
  engagementClicksTrend: [20, 30, 25, 35, 40],
  unsubscribes: 50,
  unsubscribeRateStr: '0.5%',
  repliesTotal: 100,
  themeColor: '#ffffff',
  accentColor: '#3b82f6',
  cardColor: '#f8fafc',
  textColor: '#1e293b',
  h1Color: '#0f172a',
  h2Color: '#1e293b',
  h3Color: '#334155',
  descColor: '#64748b',
  fontFamily: 'sans',
  borderRadius: 'lg',
  campaignsPerformance: [
    { id: 'cp1', name: 'Nam: Modi et in ad eum.', date: '2026-01-18', sent: 1067, opens: 1530, openRate: 0.17, uniqueOpens: 12740, uniqueOpenRate: 0.12, linkClicks: 13262, linkClickRate: 0.05, uniqueClicks: 1000, uniqueClickRate: 0.04, hardBounces: 10, softBounces: 5 }
  ]
};
